# Generated by Django 4.2.16 on 2024-11-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0003_alter_file_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='historicalfile',
            name='file',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
